version: "3"
 
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    environment:
      - DOCKER=1
    command: bundle exec  rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
volumes:
  bundle:
    driver: local
