FROM ruby:2.4.2
 
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs sqlite3 libsqlite3-dev
 
RUN mkdir /app
WORKDIR /app
 
ENV BUNDLE_JOBS=4
 
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
 
RUN bundle install --path /bundle

ADD . /app
